{
 "title": "Robotlab",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Temperature (inside)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "temp_sensor_bme280{location=\"inside\"}"
    }
   ]
  },
  {
   "title": "Humidity (inside)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "humidity_sensor_bme280{location=\"inside\"}"
    }
   ]
  },
  {
   "title": "Ari Pressure (inside)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "pressure_sensor_bme280{location=\"inside\"}/100"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "temp_sensor_bme280" }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "humidity_sensor_bme280" }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "pressure_sensor_bme280/100" }
   ]
  },
  {
   "title": "Live Stream (Camera 1)",
   "type": "text",
   "gridPos": { "h": 14, "w": 18, "x": 0, "y": 8 },
   "content": "<iframe src=\"<stream-server-here>/player.html?autoplay=1\" name=\"restreamer-player\" width=\"800\" height=\"450\" scrolling=\"no\" frameborder=\"0\" webkitallowfullscreen=\"true\" mozallowfullscreen=\"true\" allowfullscreen=\"true\"></iframe>\n<!--\n<iframe width=\"854\" height=\"480\" src=\"https://www.youtube.com/embed/LBxidLTY9Yo?autoplay=1\" frameborder=\"0\" allowfullscreen></iframe>\n-->\n\n\n"
  }
 ]
}